<a href="https://colab.research.google.com/github/Prayas-Shrestha/5CS037-2024-Prayas_Shrestha/blob/main/2408624_Prayas_Shrestha.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##PROBLEM 1 - Array Creation:

In [ ]:
#Question 1
import numpy as np
empty_array = np.empty((2,2))
print(empty_array)
print()

[[4.94510162e-310 0.00000000e+000]
 [0.00000000e+000 6.63271684e-310]]



In [ ]:
#Question 2
ones_array = np.ones((4,2))
print(ones_array)
print()

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]



In [ ]:
#Question 3
full_array = np.full((3,2),10)
print(full_array)
print()

[[10 10]
 [10 10]
 [10 10]]



In [ ]:
#Question 4
zeros_like_array = np.zeros_like(full_array)
print(zeros_like_array)
print()


[[0 0]
 [0 0]
 [0 0]]



In [ ]:
#Question 5
ones_like_array = np.ones_like(full_array)
print(ones_like_array)
print()

[[1 1]
 [1 1]
 [1 1]]



In [ ]:
#Question 6
new_list = [1,2,3,4]
array_from_list = np.array(new_list)
print(array_from_list)
print()

[1 2 3 4]



##PROBLEM 2 - Array Manipulation: Numerical Ranges and Array indexing:

In [ ]:
#Question 1
new_array = np.arange(10,50)
print(new_array)
print()

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]



In [ ]:
#Question 2
reshape_array = np.arange(0,9).reshape(3,3)
print(reshape_array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#Question 3
id_array = np.eye(3,3)
print(id_array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#Question 4
random_array = np.random.random(size = 30)
print(random_array)
print()
mean = np.mean(random_array)
print("Mean: ",mean)

[0.73747921 0.00598072 0.65998226 0.51974173 0.53708164 0.28718809
 0.60560759 0.95069563 0.89208174 0.79312257 0.5219802  0.33206385
 0.35886042 0.6203678  0.9960837  0.47848919 0.67572631 0.49800566
 0.73509313 0.63574913 0.39203166 0.28743894 0.34019786 0.59305207
 0.48392389 0.46309    0.04879386 0.34503431 0.06077481 0.45268323]

Mean:  0.5102800398587589


In [ ]:
#Question 5
random_array = np.random.random((10,10))
print(random_array)
print()
min = np.min(random_array)
max = np.max(random_array)
print("Min: ",min)
print("Max: ",max)

[[0.35829686 0.87957932 0.31013073 0.57693216 0.89138218 0.51930882
  0.93137418 0.69691764 0.86475896 0.65872326]
 [0.12049597 0.40937888 0.68467091 0.99970067 0.32660765 0.84087783
  0.19510658 0.2516181  0.58892592 0.56570092]
 [0.07675921 0.10536872 0.25762773 0.60376564 0.4376579  0.06598748
  0.00432904 0.88170242 0.66342724 0.93141467]
 [0.72223412 0.23510654 0.75149624 0.66385479 0.92000404 0.30754824
  0.35428122 0.15520244 0.62563501 0.29378959]
 [0.04886322 0.03251185 0.59674973 0.87901367 0.06169091 0.93344162
  0.20772197 0.73890913 0.34700269 0.81837121]
 [0.55346077 0.77426409 0.46203417 0.38956991 0.21349916 0.20761632
  0.64589269 0.59260097 0.84397791 0.74968091]
 [0.5948617  0.98946403 0.74633314 0.79868293 0.42411388 0.91742737
  0.67940032 0.81604786 0.95283717 0.15461441]
 [0.44220346 0.44909256 0.86592639 0.71076528 0.74060133 0.40721526
  0.4678082  0.82718486 0.70376466 0.00199802]
 [0.69487391 0.95662311 0.94056866 0.34320225 0.18108406 0.76455196
  0.62724245

In [ ]:
#Question 6
zero_array = np.zeros (10)
print(zero_array)
print()
zero_array[4] = 1
print(zero_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
#Question 7
arr = np.array([1,2,0,0,4,0])
reverse_arr = np.flip(arr)
print("Reversed array:",reverse_arr)

Reversed array: [0 4 0 0 2 1]


In [ ]:
#Question 8
twod_array = np.zeros((5,5),dtype = int)

twod_array[0, :] = 1
twod_array[-1, :] = 1
twod_array[:, 0] = 1
twod_array[:, -1] = 1

print(twod_array)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [ ]:
#Question 9
checkerboard = np.zeros(8*8,dtype = int)
checkerboard[1::2] = 1
checkerboard[::2] = 0
checkerboard = checkerboard.reshape(8,8)
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]]


##Problem 3 - Array Operations

In [ ]:
#Array Initialization
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

#Question 1
sum1 = np.add(x,y)
print("Sum of x and y: ",sum1)
print()

sum2 = np.add(v,w)
print("Sum of v and w: ",sum2)

Sum of x and y:  [[ 6  8]
 [10 13]]

Sum of v and w:  [20 22]


In [ ]:
#Question 2
diff1 = np.subtract(x,y)
print("Difference of x and y: \n",diff1)
print()

diff2 = np.subtract(v,w)
print("Difference of v and w: ",diff2)

Difference of x and y: 
 [[-4 -4]
 [-4 -3]]

Difference of v and w:  [-2 -2]


In [ ]:
#Question 3
prod = np.multiply(x,4)
print("Product of x and 4: \n",prod)
print()

prod2 = np.multiply(x,y)
print("Product of x and y: \n",prod2)
print()

prod3 = np.multiply(v,w)
print("Product of v and w: ",prod3)



Product of x and 4: 
 [[ 4  8]
 [12 20]]

Product of x and y: 
 [[ 5 12]
 [21 40]]

Product of v and w:  [ 99 120]


In [ ]:
#Question 4
sqr_x = np.power(x,2)
print("Power of x: \n",sqr_x)
print(sqr_x)
print()

sqr_v = np.power(v,2)
print("Power of v: ",sqr_v)
print()

sqr_y = np.power(y,2)
print("Power of y: \n",sqr_y)
print()

sqr_w = np.power(w,2)
print("Power of w: ",sqr_w)

Power of x: 
 [[ 1  4]
 [ 9 25]]
[[ 1  4]
 [ 9 25]]

Power of v:  [ 81 100]

Power of y: 
 [[25 36]
 [49 64]]

Power of w:  [121 144]


In [ ]:
#Question 5
rows = np.concatenate((x,y),axis = 0)
print(rows)
print()

cols = np.concatenate((x,y),axis = 1)
print(cols)

[[1 2]
 [3 5]
 [5 6]
 [7 8]]

[[1 2 5 6]
 [3 5 7 8]]


In [ ]:
#Question 6
rows = np.concatenate((x,v),axis=0)
print(rows)
print()

cols = np.concatenate((x,v),axis=1)
print(cols)


Observation:

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

##4. Matrix Operations

In [5]:
#Question 1
import numpy as np
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
#Prove A.A−1 = I.
A_inv = np.linalg.inv(A)
I = np.dot(A,A_inv)
print(I)

[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [9]:
#Question 2
#AB != BA
AB = np.matmul(A,B)
print("AB:\n",AB)
print()
BA = np.matmul(B,A)
print("BA:\n",BA)

AB:
 [[23 13]
 [51 29]]

BA:
 [[36 44]
 [13 16]]


In [15]:
#Question 3
#(AB)T = BT.AT
AB = np.matmul(A,B)
AB_T = AB.T
print("AB_T:\n",AB_T)
print()
B_T = B.T
A_T = A.T
BT_AT = np.matmul(B_T,A_T)
print("BT_AT:\n",BT_AT)

AB_T:
 [[29 36]
 [16 20]]

BT_AT:
 [[29 36]
 [16 20]]


In [18]:
#Question 4
"""

Solve for
2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

"""

A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3,  1, -1]])

B = np.array([-1,-3,9])

A_inv = np.linalg.inv(A)

X = np.dot(A_inv,B)

print("Solution for X (x,y,z):", X)

Solution for X (x,y,z): [ 2.  1. -2.]
